from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('list/', views.list_item_view, name='list_item'),
    path('categories/', views.list_item_view, name='categories'),
    path('sell/', views.list_item_view, name='sell'),
    path('subcategories/<slug:category_slug>/', views.subcategory_view, name='subcategory'),
    path('fashion/<slug:section_slug>/', views.fashion_section_view, name='fashion_section'),
    path('categories/<slug:category_slug>/<slug:section_slug>/', views.category_section_view, name='category_section'),
    path('fashion-review/', views.fashion_review_queue_view, name='fashion_review_queue'),
    path('product/<int:id>/', views.product_detail_view, name='product_detail'),
    path('product/<int:id>/report/', views.report_product_view, name='report_product'),
    path('product/<int:id>/edit/', views.edit_product_view, name='edit_product'),
    path('product/<int:id>/delete/', views.delete_product_view, name='delete_product'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/add/<int:product_id>/', views.add_to_cart_view, name='add_to_cart'),
    path('cart/remove/<int:item_id>/', views.remove_from_cart_view, name='remove_from_cart'),
    path('cart/update/<int:item_id>/', views.update_cart_item_view, name='update_cart_item'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('payments/return/', views.payment_return_view, name='payment_return'),
    path('webhooks/paystack/', views.paystack_webhook_view, name='paystack_webhook'),
    path('vendor/bank/', views.vendor_bank_view, name='vendor_bank'),
    path('vendor/payouts/', views.vendor_dashboard_view, name='vendor_dashboard'),
    path('admin/payouts/<int:payout_id>/', views.payout_approval_view, name='payout_approval'),
    path('staff/finance/', views.finance_dashboard_view, name='finance_dashboard'),
    path('profile/', views.profile_view, name='profile'),
    path('orders/<int:order_id>/report-issue/', views.report_order_issue_view, name='report_order_issue'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('tour/complete/', views.buyer_tour_complete_view, name='buyer_tour_complete'),
    path('logout/', views.logout_view, name='logout'),
]
