# Generated by Django 6.1 on 2026-10-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_accountprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='vendor_terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fashion_audience',
            field=models.CharField(blank=True, choices=[('', 'No restriction'), ('men', 'Men'), ('women', 'Women'), ('both', 'Both')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fashion_trust_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fashion_trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
