# Generated by Django 6.1 on 2026-10-02 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_fashion_categories(apps, schema_editor):
    CategoryNode = apps.get_model('products', 'CategoryNode')
    Product = apps.get_model('products', 'Product')
    fashion, _ = CategoryNode.objects.get_or_create(
        parent=None,
        slug='fashion',
        defaults={'name': 'Fashion'},
    )
    for name in ('Men', 'Women', 'Unisex'):
        CategoryNode.objects.get_or_create(
            parent=fashion,
            slug=name.lower(),
            defaults={'name': name},
        )
    Product.objects.filter(category='Fashion').update(moderation_status='pending')


def keep_seeded_categories(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_product_discount_price_and_more'),
        ('vendors', '0004_accountprofile_vendor_terms_accepted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flagged_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CategoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.categorynode')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RunPython(seed_fashion_categories, keep_seeded_categories),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.categorynode'),
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='products.product')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_product_violations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='vendors.vendor')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='categorynode',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='unique_category_node_sibling_slug'),
        ),
        migrations.AddConstraint(
            model_name='productreport',
            constraint=models.UniqueConstraint(fields=('product', 'reporter'), name='unique_reporter_product_report'),
        ),
    ]
