# Generated by Django 6.1 on 2026-10-02 13:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal, ROUND_HALF_UP


def _naira_to_kobo(value):
    if value is None:
        return None
    return int((Decimal(value) * 100).quantize(Decimal('1'), rounding=ROUND_HALF_UP))


def convert_legacy_money_to_kobo(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Order = apps.get_model('products', 'Order')
    OrderItem = apps.get_model('products', 'OrderItem')

    for product in Product.objects.all().iterator():
        product.price_kobo = _naira_to_kobo(product.price)
        product.discount_price_kobo = _naira_to_kobo(product.discount_price)
        product.save(update_fields=('price_kobo', 'discount_price_kobo'))

    for order in Order.objects.all().iterator():
        order.total_kobo = _naira_to_kobo(order.total_amount)
        order.legacy = True
        order.payment_status = 'legacy'
        order.save(update_fields=('total_kobo', 'legacy', 'payment_status'))

    for item in OrderItem.objects.select_related('product').all().iterator():
        item.price_kobo = _naira_to_kobo(item.price)
        if item.product_id:
            item.vendor_id = item.product.vendor_id
        item.save(update_fields=('price_kobo', 'vendor'))


def clear_converted_fields(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Order = apps.get_model('products', 'Order')
    OrderItem = apps.get_model('products', 'OrderItem')
    Product.objects.update(price_kobo=None, discount_price_kobo=None)
    Order.objects.update(total_kobo=None, legacy=False, payment_status='unpaid')
    OrderItem.objects.update(price_kobo=None, vendor=None)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_flagged_for_review_product_moderation_status_and_more'),
        ('vendors', '0005_vendor_bank_account_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home & Garden', 'Home & Garden'), ('Sports', 'Sports'), ('Automotive', 'Automotive'), ('Toys & Games', 'Toys & Games')], max_length=50, unique=True)),
                ('commission_bps', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('opay', 'OPay')], max_length=10)),
                ('event_key', models.CharField(max_length=128, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_commission_bps', models.PositiveSmallIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(10000)])),
                ('gateway_fee_bearer', models.CharField(choices=[('platform', 'Platform'), ('vendor', 'Vendor')], default='platform', max_length=10)),
                ('holding_period_days', models.PositiveSmallIntegerField(default=5)),
                ('minimum_withdrawal_kobo', models.PositiveBigIntegerField(default=500000)),
                ('payout_approval_threshold_kobo', models.PositiveBigIntegerField(default=0)),
                ('require_payout_approval', models.BooleanField(default=False)),
                ('weekly_auto_payouts', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_kobo',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_kobo',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_kobo',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_rate_bps',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gateway_fee_kobo',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_kobo',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_net_kobo',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price_kobo',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_kobo',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kobo', models.PositiveBigIntegerField()),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('awaiting_approval', 'Awaiting approval'), ('processing', 'Processing'), ('success', 'Successful'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='requested', max_length=20)),
                ('transfer_code', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='processing', max_length=20)),
                ('subtotal_kobo', models.PositiveBigIntegerField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('release_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('has_open_dispute', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_orders', to='products.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_orders', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='products.vendororder')),
            ],
        ),
        migrations.CreateModel(
            name='VendorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_balance_kobo', models.PositiveBigIntegerField(default=0)),
                ('available_balance_kobo', models.PositiveBigIntegerField(default=0)),
                ('total_paid_out_kobo', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('release', 'Release'), ('payout', 'Payout'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=12)),
                ('amount_kobo', models.PositiveBigIntegerField()),
                ('balance_bucket', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available')], max_length=12)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='products.payout')),
                ('vendor_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='products.vendororder')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='products.vendorwallet')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('opay', 'OPay')], max_length=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount_kobo', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100)),
                ('gateway_fee_kobo', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='products.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('order',), name='one_successful_payment_per_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='vendororder',
            constraint=models.UniqueConstraint(fields=('order', 'vendor'), name='unique_vendor_suborder'),
        ),
        migrations.RunPython(convert_legacy_money_to_kobo, clear_converted_fields),
    ]
