# Generated by Django 6.1 on 2026-10-05 19:54

from django.db import migrations, models


def seed_building_materials(apps, schema_editor):
    CategoryNode = apps.get_model('products', 'CategoryNode')
    root, _ = CategoryNode.objects.get_or_create(
        parent=None,
        slug='building-materials',
        defaults={'name': 'Building Materials'},
    )
    for name, slug in (
        ('Spanish Tiles', 'spanish-tiles'),
        ('Doors', 'doors'),
        ('Other Building Materials', 'other-building-materials'),
    ):
        CategoryNode.objects.get_or_create(parent=root, slug=slug, defaults={'name': name})


def unseed_building_materials(apps, schema_editor):
    CategoryNode = apps.get_model('products', 'CategoryNode')
    CategoryNode.objects.filter(parent__slug='building-materials', parent__parent__isnull=True).delete()
    CategoryNode.objects.filter(parent__isnull=True, slug='building-materials').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orderitem_product_name_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='material_finish',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_per_carton',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_sale',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='categorycommission',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home & Garden', 'Home & Garden'), ('Sports', 'Sports'), ('Building Materials', 'Building Materials'), ('Automotive', 'Automotive'), ('Toys & Games', 'Toys & Games')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home & Garden', 'Home & Garden'), ('Sports', 'Sports'), ('Building Materials', 'Building Materials'), ('Automotive', 'Automotive'), ('Toys & Games', 'Toys & Games')], default='Electronics', max_length=50),
        ),
        migrations.RunPython(seed_building_materials, unseed_building_materials),
    ]
