# Generated by Django 6.1 on 2026-10-05 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_country_of_origin_product_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_classified_products', to='products.categorynode'),
        ),
        migrations.AddField(
            model_name='product',
            name='classification_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='classification_reason',
            field=models.TextField(blank=True),
        ),
    ]
