# Generated by Django 6.1 on 2026-10-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_auto_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('opay', 'OPay (legacy)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentwebhookevent',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('opay', 'OPay (legacy)')], max_length=10),
        ),
    ]
